# Lints the binderhub/static/js folders content with eslint, influenced by
# ".eslintrc.js", by running "npm run lint" where "lint" is a command defined in
# package.json.
#
name: eslint

on:
  pull_request:
    paths:
      - ".github/workflows/eslint.yml"
      - ".eslintrc.js"
      - "package.json"
      - "binderhub/static/js/**"
      - "js/**"
  push:
    paths:
      - ".github/workflows/eslint.yml"
      - ".eslintrc.js"
      - "package.json"
      - "binderhub/static/js/**"
      - "js/**"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
      - "update-*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read # actions/checkout
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - run: npm install

      - run: npm run lint
