# Runs jest based unit tests for frontend javascript and @jupyterhub/binderhub-client
name: "JS Unit tests"

on:
  pull_request:
    paths:
      - "binderhub/static/js/**"
      - "js/packages/binderhub-client/**"
      - ".github/workflows/jest.yml"
  push:
    paths:
      - "binderhub/static/js/**"
      - "js/packages/binderhub-client/**"
      - ".github/workflows/jest.yml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
      - "update-*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read # actions/checkout
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: "Setup dependencies"
        run: |
          npm install

      - name: "Run all unit tests"
        run: |
          npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
